# Generated by Django 6.0.4 on 2026-04-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
